server:
  port: 8090

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

# Activar consola web de H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console